### ISSUE TITLE
[REFACTOR] Attendance CheckIn, CheckOut 리팩토링

### ISSUE THREAD

**Issue by ToySin** [saveme-cadet/LMS-BE#113]
# ISSUE : :refactor: Refactor
Attendance 출석부에 CheckIn, CheckOut 기능을 리팩토링하여 구현한다.
***
#Description
- attendanceId를 pathVariable로 받는 api로 리팩토링한다.
- 도메인 모델링 패턴 적용
- 점수와 관련된 통계는 따로 작성 -> day_statistical_data 관련 도메인 작성 시 예정
***
# Todo
- [x] CheckIn, CheckOut 상태를 따로 분리하지않고, AttendanceStatus 하나로 통합한다.
- [x] 비즈니스 로직으로 CheckIn, CheckOut 추가 (Entity에서)
- [ ] 조회용 DTO 생성
# ETC
기타사항
***
